import {NavLink} from "../models/models";

export  const ALL_MEDICAL_SERVICES: NavLink[] = [
  { name: 'Adolescent Epilepsy Care', url: '/medical-services/adolescent-epilepsy' },
  { name: 'Adult Asthma Care', url: '/services/adult-asthma' },
  { name: 'Adult Congenital Heart Disease', url: '/services/adult-congenital-heart' },
  { name: 'Adult Epilepsy', url: '/services/adult-epilepsy' },
  { name: 'Advanced Heart Failure', url: '/services/advanced-heart-failure' },
  { name: 'Allergy and Immunology', url: '/services/allergy-immunology' },
  { name: 'Alzheimer\'s Care', url: '/services/alzheimers-care' },
  { name: 'Aortic Care', url: '/services/aortic-care' },
  { name: 'Audiology', url: '/medical-services/audiology' },
  { name: 'Bariatric Surgery', url: '/services/bariatric-surgery' },
  { name: 'Behavioral Health', url: '/services/behavioral-health' },
  { name: 'Behavioral Neurology', url: '/services/behavioral-neurology' },
  { name: 'Bladder Cancer', url: '/services/bladder-cancer' },
  { name: 'Bone Marrow/Stem Cell Transplant (BMT)', url: '/services/bone-marrow-stem-cell-transplant-bmt' },
  { name: 'Brain Tumor', url: '/services/brain-tumor' },
  { name: 'Breast Cancer', url: '/services/breast-cancer' },
  { name: 'Breast Imaging', url: '/services/breast-imaging' },
  { name: 'Burn Treatment', url: '/services/burn-treatment' },
  { name: 'Cancer Genetics', url: '/services/cancer-genetics' },
  { name: 'Cancer Services', url: '/services/cancer-services' },
  { name: 'Cardiac Rehabilitation', url: '/services/cardiac-rehabilitation' },
  { name: 'Cardio-Oncology', url: '/services/cardio-oncology' },
  { name: 'Cataract Surgery', url: '/services/cataract-surgery' },
  { name: 'Celiac Disease', url: '/services/celiac-disease' },
  { name: 'Cerebral Palsy', url: '/services/cerebral-palsy' },
  { name: 'Cerebrovascular Neurosurgery', url: '/services/cerebrovascular-neurosurgery' },
  { name: 'Child Life Specialists', url: '/services/child-life-specialists' },
  { name: 'Chimeric Antigen Receptor (CAR) T-cell Therapy', url: '/services/chimeric-antigen-receptor-t-cell-therapy' },
  { name: 'Chronic Obstructive Pulmonary Disease (COPD)', url: '/services/chronic-obstructive-pulmonary-disease-copd' },
  { name: 'Connective Tissue Disease-Interstitial Lung Disease (CTD-ILD)', url: '/services/connective-tissue-disease-interstitial-lung-disease-ctd-ild' },
  { name: 'Contact Lenses', url: '/services/contact-lenses' },
  { name: 'Corneal Disorders & Uveitis', url: '/services/corneal-disorders-uveitis' },
  { name: 'Corneal Transplant', url: '/services/corneal-transplant' },
  { name: 'Cystic Fibrosis', url: '/services/cystic-fibrosis' },
  { name: 'Dementia Services', url: '/services/dementia-services' },
  { name: 'Dermatology', url: '/services/dermatology' },
  { name: 'Diabetes', url: '/services/diabetes' },
  { name: 'Digestive Diseases', url: '/services/digestive-diseases' },
  { name: 'Digestive Diseases Nutrition', url: '/services/digestive-diseases-nutrition' },
  { name: 'Dry Eye', url: '/services/dry-eye' },
  { name: 'East-West Medicine', url: '/services/east-west-medicine' },
  { name: 'Eating Disorders', url: '/services/eating-disorders' },
  { name: 'Emergency Medicine', url: '/services/emergency-medicine' },
  { name: 'Endocrine Surgery', url: '/services/endocrine-surgery' },
  { name: 'Endocrinology', url: '/services/endocrinology' },
  { name: 'Epilepsy Surgery', url: '/services/epilepsy-surgery' },
  { name: 'Esophageal Cancer', url: '/services/esophageal-cancer' },
  { name: 'Esophageal Health', url: '/services/esophageal-health' },
  { name: 'Extensivist Medicine', url: '/services/extensivist-medicine' },
  { name: 'Extracorporeal Membrane Oxygenation (ECMO)', url: '/services/extracorporeal-membrane-oxygenation-ecmo' },
  { name: 'Facial Plastic Surgery and Rejuvenation', url: '/services/facial-plastic-surgery-rejuvenation' },
  { name: 'Family Planning', url: '/services/family-planning' },
  { name: 'Fertility & Reproductive Health', url: '/services/fertility-reproductive-health' },
  { name: 'Fibroid Care', url: '/services/fibroid-care' },
  { name: 'Food Allergy', url: '/services/food-allergy' },
  { name: 'Foot and Ankle Surgery', url: '/services/foot-and-ankle-surgery' },
  { name: 'Gastrointestinal Cancer', url: '/services/gastrointestinal-cancer' },
  { name: 'Gender Health', url: '/services/gender-health' },
  { name: 'General Neurology', url: '/services/general-neurology' },
  { name: 'General Orthopaedics', url: '/services/general-orthopaedics' },
  { name: 'General Pediatrics', url: '/services/general-pediatrics' },
  { name: 'General Surgery', url: '/services/general-surgery' },
  { name: 'Genetic Heart Disease', url: '/services/genetic-heart-disease' },
  { name: 'Geriatric Medicine', url: '/services/geriatric-medicine' },
  { name: 'GI Motility', url: '/services/gi-motility' },
  { name: 'Glaucoma Care', url: '/services/glaucoma-care' },
  { name: 'Gout Care', url: '/services/gout-care' },
  { name: 'Gynecologic Oncology', url: '/services/gynecologic-oncology' },
  { name: 'Gynecology', url: '/services/gynecology' },
  { name: 'Hand Surgery', url: '/services/hand-surgery' },
  { name: 'Hand Transplant', url: '/services/hand-transplant' },
  { name: 'Head & Neck Cancer', url: '/services/head-neck-cancer' },
  { name: 'Head & Neck Surgery', url: '/services/head-neck-surgery' },
  { name: 'Heart & Vascular Services', url: '/services/heart-vascular-services' },
  { name: 'Heart and Liver Disease', url: '/services/heart-and-liver-disease' },
  { name: 'Heart Surgery', url: '/services/heart-surgery' },
  { name: 'Heart Transplant', url: '/services/heart-transplant' },
  { name: 'Hepatology', url: '/services/hepatology' },
  { name: 'Hereditary Hemorrhagic Telangiectasia', url: '/services/hereditary-hemorrhagic-telangiectasia' },
  { name: 'Hernia Care', url: '/services/hernia-care' },
  { name: 'Hospitalists', url: '/services/hospitalists' },
  { name: 'Hyperbaric Oxygen Therapy', url: '/services/hyperbaric-oxygen-therapy' },
  { name: 'Hyperthermic Intraperitoneal Chemotherapy (HIPEC)', url: '/services/hyperthermic-intraperitoneal-chemotherapy-hipec' },
  { name: 'IBS and Other Disorders of the Gut-Brain Interactions', url: '/services/ibs-and-other-disorders-of-the-gut-brain-interactions' },
  { name: 'Immunology', url: '/services/immunology' },
  { name: 'Infectious Diseases', url: '/services/infectious-diseases' },
  { name: 'Inflammatory Bowel Diseases (IBD)', url: '/services/inflammatory-bowel-diseases-ibd' },
  { name: 'Insurance-Based Weight Loss', url: '/services/insurance-based-weight-loss' },
  { name: 'Integrative Medicine', url: '/services/integrative-medicine' },
  { name: 'Integrative Oncology', url: '/services/integrative-oncology' },
  { name: 'Internal Medicine-Pediatrics', url: '/services/internal-medicine-pediatrics' },
  { name: 'Interstitial Lung Disease (ILD)', url: '/services/interstitial-lung-disease-ild' },
  { name: 'Interventional Cardiology', url: '/services/interventional-cardiology' },
  { name: 'Interventional Endoscopy', url: '/services/interventional-endoscopy' },
  { name: 'Interventional Neuroradiology', url: '/services/interventional-neuroradiology' },
  { name: 'Interventional Oncology', url: '/services/interventional-oncology' },
  { name: 'Interventional Radiology', url: '/services/interventional-radiology' },
  { name: 'Interventional Radiology for Varicose Veins', url: '/services/interventional-radiology-for-varicose-veins' },
  { name: 'Islet Cell Transplant', url: '/services/islet-cell-transplant' },
  { name: 'IVC Filter Clinic', url: '/services/ivc-filter-clinic' },
  { name: 'Joint Replacement', url: '/services/joint-replacement' },
  { name: 'Kidney Cancer', url: '/services/kidney-cancer' },
  { name: 'Kidney Exchange', url: '/services/kidney-exchange' },
  { name: 'Kidney Health', url: '/services/kidney-health' },
  { name: 'Kidney Stones & Urinary Obstruction', url: '/services/kidney-stones-urinary-obstruction' },
  { name: 'Kidney Transplant', url: '/services/kidney-transplant' },
  { name: 'Labor & Delivery', url: '/services/labor-delivery' },
  { name: 'Leukemia & Lymphoma', url: '/services/leukemia-lymphoma' },
  { name: 'Liver Cancer', url: '/services/liver-cancer' },
  { name: 'Liver Disease in Asians', url: '/services/liver-disease-in-asians' },
  { name: 'Liver Transplant', url: '/services/liver-transplant' },
  { name: 'Long COVID', url: '/services/long-covid' },
  { name: 'Lung Cancer', url: '/services/lung-cancer' },
  { name: 'Lung Transplant', url: '/services/lung-transplant' },
  { name: 'Lupus Care', url: '/services/lupus-care' },
  { name: 'Maternal-Fetal Medicine', url: '/services/maternal-fetal-medicine' },
  { name: 'Mesothelioma', url: '/services/mesothelioma' },
  { name: 'Migraine Treatment', url: '/services/migraine-treatment' },
  { name: 'Minimally Invasive Gynecologic Surgery', url: '/services/min-invasive-gynecologic-surgery' },
  { name: 'Minimally Invasive Urology Surgery', url: '/services/min-invasive-urology-surgery' },
  { name: 'Monkeypox', url: '/services/monkeypox' },
  { name: 'Multidisciplinary Complex Amputation', url: '/services/multidisciplinary-complex-amputation' },
  { name: 'Multiple Sclerosis', url: '/services/multiple-sclerosis' },
  { name: 'Music Therapy', url: '/services/music-therapy' },
  { name: 'Myositis Care', url: '/services/myositis-care' },
  { name: 'Neonatology & Developmental Biology', url: '/services/neonatology-developmental-biology' },
  { name: 'Nephrology', url: '/services/nephrology' },
  { name: 'Neuro-Infectious Diseases', url: '/services/neuro-infectious-diseases' },
  { name: 'Neuro-Oncology', url: '/services/neuro-oncology' },
  { name: 'Neuro-ophthalmology', url: '/services/neuro-ophthalmology' },
  { name: 'Neuro-Otology', url: '/services/neuro-otology' },
  { name: 'Neuro-Rehabilitation', url: '/services/neuro-rehabilitation' },
  { name: 'Neurocritical Care', url: '/services/neurocritical-care' },
  { name: 'Neurogenetics', url: '/services/neurogenetics' },
  { name: 'Neurology', url: '/services/neurology' },
  { name: 'Neuromodulation', url: '/services/neuromodulation' },
  { name: 'Neuromuscular Disorders & Diseases', url: '/services/neuromuscular-disorders-diseases' },
  { name: 'Neurosurgery', url: '/services/neurosurgery' },
  { name: 'Neurotrauma', url: '/services/neurotrauma' },
  { name: 'Nuclear Medicine', url: '/services/nuclear-medicine' },
  { name: 'Nurse Midwives', url: '/services/nurse-midwives' },
  { name: 'Obesity and Metabolic Health', url: '/services/obesity-and-metabolic-health' },
  { name: 'Obstetrics and Gynecology (OB/GYN)', url: '/services/obstetrics-and-gynecology-ob-gyn' },
  { name: 'Ophthalmic Oncology', url: '/services/ophthalmic-oncology' },
  { name: 'Ophthalmology', url: '/services/ophthalmology' },
  { name: 'Optometry', url: '/services/optometry' },
  { name: 'Orbital and Ophthalmic Plastic Surgery', url: '/services/orbital-and-ophthalmic-plastic-surgery' },
  { name: 'Orthopaedic Oncology', url: '/services/orthopaedic-oncology' },
  { name: 'Orthopaedic Trauma', url: '/services/orthopaedic-trauma' },
  { name: 'Orthopedic Surgery', url: '/services/orthopedic-surgery' },
  { name: 'Orthopedics & Sports Medicine', url: '/services/orthopedics-sports-medicine' },
  { name: 'Outpatient Nutrition Services', url: '/services/outpatient-nutrition-services' },
  { name: 'Pain Management', url: '/services/pain-management' },
  { name: 'Palliative Care', url: '/services/palliative-care' },
  { name: 'Pancreas Transplant', url: '/services/pancreas-transplant' },
  { name: 'Pancreatic Cancer', url: '/services/pancreatic-cancer' },
  { name: 'Pancreatic Diseases', url: '/services/pancreatic-diseases' },
  { name: 'Pathology & Laboratory Medicine', url: '/services/pathology-laboratory-medicine' },
  { name: 'Pediatric Brain Tumors', url: '/services/pediatric-brain-tumors' },
  { name: 'Pediatric Cancer', url: '/services/pediatric-cancer' },
  { name: 'Pediatric Cardiology', url: '/services/pediatric-cardiology' },
  { name: 'Pediatric Congenital Heart Disease', url: '/services/pediatric-congenital-heart-disease' },
  { name: 'Pediatric Infectious Diseases', url: '/services/pediatric-infectious-diseases' },
  { name: 'Pediatric Intestinal and Multivisceral Transplant', url: '/services/pediatric-intestinal-and-multivisceral-transplant' },
  { name: 'Radiation Oncology', url: '/services/radiation-oncology' },
  { name: 'Radiology', url: '/services/radiology' },
  { name: 'Rape Treatment Center', url: '/services/rape-treatment-center' },
  { name: 'Refractive Surgery & Vision Correction', url: '/services/refractive-surgery-vision-correction' },
  { name: 'Rehabilitation Services & Care', url: '/services/rehabilitation-services-care' },
  { name: 'Reproductive Genetics', url: '/services/reproductive-genetics' },
  { name: 'Respiratory Care', url: '/services/respiratory-care' },
  { name: 'Retina Disease Care', url: '/services/retina-disease-care' },
  { name: 'Retinal Disorders & Ophthalmic Genetics', url: '/services/retinal-disorders-ophthalmic-genetics' },
  { name: 'Rheumatology', url: '/services/rheumatology' },
  { name: 'Robotic Surgery', url: '/services/robotic-surgery' },
  { name: 'Sarcoma', url: '/services/sarcoma' },
  { name: 'Scleroderma Care', url: '/services/scleroderma-care' },
  { name: 'Second Opinion', url: '/services/second-opinion' },
  { name: 'Shoulder and Elbow Surgery', url: '/services/shoulder-and-elbow-surgery' },
  { name: 'Sickle Cell Disease Care', url: '/services/sickle-cell-disease-care' },
  { name: 'Skeletal Dysplasia', url: '/services/skeletal-dysplasia' },
  { name: 'Skin Cancer', url: '/services/skin-cancer' },
  { name: 'Sleep Medicine', url: '/services/sleep-medicine' },
  { name: 'Small Bowel Endoscopy', url: '/services/small-bowel-endoscopy' },
  { name: 'South Asian Heart Health', url: '/services/south-asian-heart-health' },
  { name: 'Speech Pathology', url: '/services/speech-pathology' },
  { name: 'Spine Care', url: '/services/spine-care' },
  { name: 'Sports Cardiology', url: '/services/sports-cardiology' },
  { name: 'Sports Concussion and Traumatic Brain Injury', url: '/services/sports-concussion-and-traumatic-brain-injury' },
  { name: 'Sports Medicine', url: '/services/sports-medicine' },
  { name: 'Stomach Cancer', url: '/services/stomach-cancer' },
  { name: 'Stroke', url: '/services/stroke' },
  { name: 'Surgery', url: '/services/surgery' },
  { name: 'Surgical Oncology', url: '/services/surgical-oncology' },
  { name: 'Testicular Cancer', url: '/services/testicular-cancer' },
  { name: 'The Men\'s Clinic at UCLA', url: '/services/the-mens-clinic-at-ucla' },
  { name: 'Theranostics', url: '/services/theranostics' },
  { name: 'Thoracic Surgery', url: '/services/thoracic-surgery' },
  { name: 'Thyroid Care', url: '/services/thyroid-care' },
  { name: 'Transplant Services', url: '/services/transplant-services' },
  { name: 'Tumor-Infiltrating Lymphocyte (TIL) Therapy', url: '/services/tumor-infiltrating-lymphocyte-til-therapy' },
  { name: 'UCLA Health Well Check', url: '/services/ucla-health-well-check' },
  { name: 'UCLA Levine Family Center for Movement Disorders', url: '/services/ucla-levine-family-center-for-movement-disorders' },
  { name: 'Urogynecology & Pelvic Health', url: '/services/urogynecology-pelvic-health' },
  { name: 'Urologic Oncology', url: '/services/urologic-oncology' },
  { name: 'Urology', url: '/services/urology' },
  { name: 'Vascular and Endovascular Surgery', url: '/services/vascular-and-endovascular-surgery' },
  { name: 'Vascular Surgery for Varicose Veins', url: '/services/vascular-surgery-for-varicose-veins' },
  { name: 'Vasculitis Care', url: '/services/vasculitis-care' },
  { name: 'Vision Rehabilitation', url: '/services/vision-rehabilitation' },
  { name: 'Von Hippel-Lindau (VHL) Disease', url: '/services/von-hippel-lindau-vhl-disease' },
  { name: 'Walter and Shirley Wang Center for Integrative Digestive Health', url: '/services/walter-and-shirley-wang-center-for-integrative-digestive-health' },
  { name: 'Weight Management', url: '/services/weight-management' },
  { name: 'Women\'s Health & OBGYN Services', url: '/services/womens-health-obgyn-services' },
  { name: 'Women’s Cardiovascular Services', url: '/services/womens-cardiovascular-services' }
];

export const LETTERS = 'ABCDEFGHIJKLMNOPRSTUVW'.split('');

export const LOREM_NAV_LINK: NavLink[] = [
  { name: 'About the Medical Center', url: '/about-us' },
  { name: 'For Patient & Visitors', url: '/patients-visitors' },
  { name: 'Health Resources', url: '/health-resources' },
  { name: 'Our Units & Floors', url: '/units-floors' }
];

export const ADOLESCENT_EPILEPSY_CARE_NAV_LINK: NavLink[] = [
  { name: 'About the Medical Center', url: '/about-us' },
  { name: 'For Patient & Visitors', url: '/patients-visitors' },
  { name: 'Health Resources', url: '/health-resources' },
  { name: 'Our Units & Floors', url: '/units-floors' }
];

export const AUDIOLOGY_NAV_LINK: NavLink[] = [
  { name: 'About the Medical Center', url: '/about-us' },
  { name: 'For Patient & Visitors', url: '/patients-visitors' },
  { name: 'Health Resources', url: '/health-resources' },
  { name: 'Our Units & Floors', url: '/units-floors' }
];
