import {MedicalService} from "../models/MedicalService";

export  const ALL_MEDICAL_SERVICES: MedicalService[] = [
  { name: 'Adolescent Epilepsy Care', route: '/services/adolescent-epilepsy' },
  { name: 'Adult Asthma Care', route: '/services/adult-asthma' },
  { name: 'Adult Congenital Heart Disease', route: '/services/adult-congenital-heart' },
  { name: 'Adult Epilepsy', route: '/services/adult-epilepsy' },
  { name: 'Advanced Heart Failure', route: '/services/advanced-heart-failure' },
  { name: 'Allergy and Immunology', route: '/services/allergy-immunology' },
  { name: 'Alzheimer\'s Care', route: '/services/alzheimers-care' },
  { name: 'Aortic Care', route: '/services/aortic-care' },
  { name: 'Audiology', route: '/services/audiology' },
  { name: 'Bariatric Surgery', route: '/services/bariatric-surgery' },
  { name: 'Behavioral Health', route: '/services/behavioral-health' },
  { name: 'Behavioral Neurology', route: '/services/behavioral-neurology' },
  { name: 'Bladder Cancer', route: '/services/bladder-cancer' },
  { name: 'Bone Marrow/Stem Cell Transplant (BMT)', route: '/services/bone-marrow-stem-cell-transplant-bmt' },
  { name: 'Brain Tumor', route: '/services/brain-tumor' },
  { name: 'Breast Cancer', route: '/services/breast-cancer' },
  { name: 'Breast Imaging', route: '/services/breast-imaging' },
  { name: 'Burn Treatment', route: '/services/burn-treatment' },
  { name: 'Cancer Genetics', route: '/services/cancer-genetics' },
  { name: 'Cancer Services', route: '/services/cancer-services' },
  { name: 'Cardiac Rehabilitation', route: '/services/cardiac-rehabilitation' },
  { name: 'Cardio-Oncology', route: '/services/cardio-oncology' },
  { name: 'Cataract Surgery', route: '/services/cataract-surgery' },
  { name: 'Celiac Disease', route: '/services/celiac-disease' },
  { name: 'Cerebral Palsy', route: '/services/cerebral-palsy' },
  { name: 'Cerebrovascular Neurosurgery', route: '/services/cerebrovascular-neurosurgery' },
  { name: 'Child Life Specialists', route: '/services/child-life-specialists' },
  { name: 'Chimeric Antigen Receptor (CAR) T-cell Therapy', route: '/services/chimeric-antigen-receptor-t-cell-therapy' },
  { name: 'Chronic Obstructive Pulmonary Disease (COPD)', route: '/services/chronic-obstructive-pulmonary-disease-copd' },
  { name: 'Chronic Pelvic Pain', route: '/services/chronic-pelvic-pain' },
  { name: 'Clinical Genetics', route: '/services/clinical-genetics' },
  { name: 'Clinical Nutrition', route: '/services/clinical-nutrition' },
  { name: 'Colorectal Cancer', route: '/services/colorectal-cancer' },
  { name: 'Colorectal Surgery', route: '/services/colorectal-surgery' },
  { name: 'Complex Airway Surgery for Adults', route: '/services/complex-airway-surgery-for-adults' },
  { name: 'Complex Pediatric Airway Reconstruction, Swallowing and Tracheostomy', route: '/services/complex-pediatric-airway-reconstruction-swallowing-tracheostomy' },
  { name: 'Comprehensive Menopause Care', route: '/services/comprehensive-menopause-care' },
  { name: 'Comprehensive Ophthalmology', route: '/services/comprehensive-ophthalmology' },
  { name: 'Connective Tissue Disease-Interstitial Lung Disease (CTD-ILD)', route: '/services/connective-tissue-disease-interstitial-lung-disease-ctd-ild' },
  { name: 'Contact Lenses', route: '/services/contact-lenses' },
  { name: 'Corneal Disorders & Uveitis', route: '/services/corneal-disorders-uveitis' },
  { name: 'Corneal Transplant', route: '/services/corneal-transplant' },
  { name: 'Cystic Fibrosis', route: '/services/cystic-fibrosis' },
  { name: 'Dementia Services', route: '/services/dementia-services' },
  { name: 'Dermatology', route: '/services/dermatology' },
  { name: 'Diabetes', route: '/services/diabetes' },
  { name: 'Digestive Diseases', route: '/services/digestive-diseases' },
  { name: 'Digestive Diseases Nutrition', route: '/services/digestive-diseases-nutrition' },
  { name: 'Dry Eye', route: '/services/dry-eye' },
  { name: 'East-West Medicine', route: '/services/east-west-medicine' },
  { name: 'Eating Disorders', route: '/services/eating-disorders' },
  { name: 'Emergency Medicine', route: '/services/emergency-medicine' },
  { name: 'Endocrine Surgery', route: '/services/endocrine-surgery' },
  { name: 'Endocrinology', route: '/services/endocrinology' },
  { name: 'Epilepsy Surgery', route: '/services/epilepsy-surgery' },
  { name: 'Esophageal Cancer', route: '/services/esophageal-cancer' },
  { name: 'Esophageal Health', route: '/services/esophageal-health' },
  { name: 'Extensivist Medicine', route: '/services/extensivist-medicine' },
  { name: 'Extracorporeal Membrane Oxygenation (ECMO)', route: '/services/extracorporeal-membrane-oxygenation-ecmo' },
  { name: 'Facial Plastic Surgery and Rejuvenation', route: '/services/facial-plastic-surgery-rejuvenation' },
  { name: 'Family Planning', route: '/services/family-planning' },
  { name: 'Fertility & Reproductive Health', route: '/services/fertility-reproductive-health' },
  { name: 'Fibroid Care', route: '/services/fibroid-care' },
  { name: 'Food Allergy', route: '/services/food-allergy' },
  { name: 'Foot and Ankle Surgery', route: '/services/foot-and-ankle-surgery' },
  { name: 'Gastrointestinal Cancer', route: '/services/gastrointestinal-cancer' },
  { name: 'Gender Health', route: '/services/gender-health' },
  { name: 'General Neurology', route: '/services/general-neurology' },
  { name: 'General Orthopaedics', route: '/services/general-orthopaedics' },
  { name: 'General Pediatrics', route: '/services/general-pediatrics' },
  { name: 'General Surgery', route: '/services/general-surgery' },
  { name: 'Genetic Heart Disease', route: '/services/genetic-heart-disease' },
  { name: 'Geriatric Medicine', route: '/services/geriatric-medicine' },
  { name: 'GI Motility', route: '/services/gi-motility' },
  { name: 'Glaucoma Care', route: '/services/glaucoma-care' },
  { name: 'Gout Care', route: '/services/gout-care' },
  { name: 'Gynecologic Oncology', route: '/services/gynecologic-oncology' },
  { name: 'Gynecology', route: '/services/gynecology' },
  { name: 'Hand Surgery', route: '/services/hand-surgery' },
  { name: 'Hand Transplant', route: '/services/hand-transplant' },
  { name: 'Head & Neck Cancer', route: '/services/head-neck-cancer' },
  { name: 'Head & Neck Surgery', route: '/services/head-neck-surgery' },
  { name: 'Heart & Vascular Services', route: '/services/heart-vascular-services' },
  { name: 'Heart and Liver Disease', route: '/services/heart-and-liver-disease' },
  { name: 'Heart Surgery', route: '/services/heart-surgery' },
  { name: 'Heart Transplant', route: '/services/heart-transplant' },
  { name: 'Hepatology', route: '/services/hepatology' },
  { name: 'Hereditary Hemorrhagic Telangiectasia', route: '/services/hereditary-hemorrhagic-telangiectasia' },
  { name: 'Hernia Care', route: '/services/hernia-care' },
  { name: 'Hospitalists', route: '/services/hospitalists' },
  { name: 'Hyperbaric Oxygen Therapy', route: '/services/hyperbaric-oxygen-therapy' },
  { name: 'Hyperthermic Intraperitoneal Chemotherapy (HIPEC)', route: '/services/hyperthermic-intraperitoneal-chemotherapy-hipec' },
  { name: 'IBS and Other Disorders of the Gut-Brain Interactions', route: '/services/ibs-and-other-disorders-of-the-gut-brain-interactions' },
  { name: 'Immunology', route: '/services/immunology' },
  { name: 'Infectious Diseases', route: '/services/infectious-diseases' },
  { name: 'Inflammatory Bowel Diseases (IBD)', route: '/services/inflammatory-bowel-diseases-ibd' },
  { name: 'Insurance-Based Weight Loss', route: '/services/insurance-based-weight-loss' },
  { name: 'Integrative Medicine', route: '/services/integrative-medicine' },
  { name: 'Integrative Oncology', route: '/services/integrative-oncology' },
  { name: 'Internal Medicine-Pediatrics', route: '/services/internal-medicine-pediatrics' },
  { name: 'Interstitial Lung Disease (ILD)', route: '/services/interstitial-lung-disease-ild' },
  { name: 'Interventional Cardiology', route: '/services/interventional-cardiology' },
  { name: 'Interventional Endoscopy', route: '/services/interventional-endoscopy' },
  { name: 'Interventional Neuroradiology', route: '/services/interventional-neuroradiology' },
  { name: 'Interventional Oncology', route: '/services/interventional-oncology' },
  { name: 'Interventional Radiology', route: '/services/interventional-radiology' },
  { name: 'Interventional Radiology for Varicose Veins', route: '/services/interventional-radiology-for-varicose-veins' },
  { name: 'Islet Cell Transplant', route: '/services/islet-cell-transplant' },
  { name: 'IVC Filter Clinic', route: '/services/ivc-filter-clinic' },
  { name: 'Joint Replacement', route: '/services/joint-replacement' },
  { name: 'Kidney Cancer', route: '/services/kidney-cancer' },
  { name: 'Kidney Exchange', route: '/services/kidney-exchange' },
  { name: 'Kidney Health', route: '/services/kidney-health' },
  { name: 'Kidney Stones & Urinary Obstruction', route: '/services/kidney-stones-urinary-obstruction' },
  { name: 'Kidney Transplant', route: '/services/kidney-transplant' },
  { name: 'Labor & Delivery', route: '/services/labor-delivery' },
  { name: 'Leukemia & Lymphoma', route: '/services/leukemia-lymphoma' },
  { name: 'Liver Cancer', route: '/services/liver-cancer' },
  { name: 'Liver Disease in Asians', route: '/services/liver-disease-in-asians' },
  { name: 'Liver Transplant', route: '/services/liver-transplant' },
  { name: 'Long COVID', route: '/services/long-covid' },
  { name: 'Lung Cancer', route: '/services/lung-cancer' },
  { name: 'Lung Transplant', route: '/services/lung-transplant' },
  { name: 'Lupus Care', route: '/services/lupus-care' },
  { name: 'Maternal-Fetal Medicine', route: '/services/maternal-fetal-medicine' },
  { name: 'Mesothelioma', route: '/services/mesothelioma' },
  { name: 'Migraine Treatment', route: '/services/migraine-treatment' },
  { name: 'Minimally Invasive Gynecologic Surgery', route: '/services/min-invasive-gynecologic-surgery' },
  { name: 'Minimally Invasive Urology Surgery', route: '/services/min-invasive-urology-surgery' },
  { name: 'Monkeypox', route: '/services/monkeypox' },
  { name: 'Multidisciplinary Complex Amputation', route: '/services/multidisciplinary-complex-amputation' },
  { name: 'Multiple Sclerosis', route: '/services/multiple-sclerosis' },
  { name: 'Music Therapy', route: '/services/music-therapy' },
  { name: 'Myositis Care', route: '/services/myositis-care' },
  { name: 'Neonatology & Developmental Biology', route: '/services/neonatology-developmental-biology' },
  { name: 'Nephrology', route: '/services/nephrology' },
  { name: 'Neuro-Infectious Diseases', route: '/services/neuro-infectious-diseases' },
  { name: 'Neuro-Oncology', route: '/services/neuro-oncology' },
  { name: 'Neuro-ophthalmology', route: '/services/neuro-ophthalmology' },
  { name: 'Neuro-Otology', route: '/services/neuro-otology' },
  { name: 'Neuro-Rehabilitation', route: '/services/neuro-rehabilitation' },
  { name: 'Neurocritical Care', route: '/services/neurocritical-care' },
  { name: 'Neurogenetics', route: '/services/neurogenetics' },
  { name: 'Neurology', route: '/services/neurology' },
  { name: 'Neuromodulation', route: '/services/neuromodulation' },
  { name: 'Neuromuscular Disorders & Diseases', route: '/services/neuromuscular-disorders-diseases' },
  { name: 'Neurosurgery', route: '/services/neurosurgery' },
  { name: 'Neurotrauma', route: '/services/neurotrauma' },
  { name: 'Nuclear Medicine', route: '/services/nuclear-medicine' },
  { name: 'Nurse Midwives', route: '/services/nurse-midwives' },
  { name: 'Obesity and Metabolic Health', route: '/services/obesity-and-metabolic-health' },
  { name: 'Obstetrics and Gynecology (OB/GYN)', route: '/services/obstetrics-and-gynecology-ob-gyn' },
  { name: 'Ophthalmic Oncology', route: '/services/ophthalmic-oncology' },
  { name: 'Ophthalmology', route: '/services/ophthalmology' },
  { name: 'Optometry', route: '/services/optometry' },
  { name: 'Orbital and Ophthalmic Plastic Surgery', route: '/services/orbital-and-ophthalmic-plastic-surgery' },
  { name: 'Orthopaedic Oncology', route: '/services/orthopaedic-oncology' },
  { name: 'Orthopaedic Trauma', route: '/services/orthopaedic-trauma' },
  { name: 'Orthopedic Surgery', route: '/services/orthopedic-surgery' },
  { name: 'Orthopedics & Sports Medicine', route: '/services/orthopedics-sports-medicine' },
  { name: 'Outpatient Nutrition Services', route: '/services/outpatient-nutrition-services' },
  { name: 'Pain Management', route: '/services/pain-management' },
  { name: 'Palliative Care', route: '/services/palliative-care' },
  { name: 'Pancreas Transplant', route: '/services/pancreas-transplant' },
  { name: 'Pancreatic Cancer', route: '/services/pancreatic-cancer' },
  { name: 'Pancreatic Diseases', route: '/services/pancreatic-diseases' },
  { name: 'Pathology & Laboratory Medicine', route: '/services/pathology-laboratory-medicine' },
  { name: 'Pediatric Brain Tumors', route: '/services/pediatric-brain-tumors' },
  { name: 'Pediatric Cancer', route: '/services/pediatric-cancer' },
  { name: 'Pediatric Cardiology', route: '/services/pediatric-cardiology' },
  { name: 'Pediatric Congenital Heart Disease', route: '/services/pediatric-congenital-heart-disease' },
  { name: 'Pediatric Craniofacial Specialty Care', route: '/services/pediatric-craniofacial-specialty-care' },
  { name: 'Pediatric Critical Care', route: '/services/pediatric-critical-care' },
  { name: 'Pediatric Endocrinology', route: '/services/pediatric-endocrinology' },
  { name: 'Pediatric Gastroenterology', route: '/services/pediatric-gastroenterology' },
  { name: 'Pediatric Heart Transplant', route: '/services/pediatric-heart-transplant' },
  { name: 'Pediatric Hematology Oncology', route: '/services/pediatric-hematology-oncology' },
  { name: 'Pediatric Hospital Medicine', route: '/services/pediatric-hospital-medicine' },
  { name: 'Pediatric Imaging', route: '/services/pediatric-imaging' },
  { name: 'Pediatric Infectious Diseases', route: '/services/pediatric-infectious-diseases' },
  { name: 'Pediatric Inflammatory Bowel Disease (IBD)', route: '/services/pediatric-inflammatory-bowel-disease-ibd' },
  { name: 'Pediatric Intestinal and Multivisceral Transplant', route: '/services/pediatric-intestinal-and-multivisceral-transplant' },
  { name: 'Pediatric Liver Transplant', route: '/services/pediatric-liver-transplant' },
  { name: 'Pediatric Medical Home', route: '/services/pediatric-medical-home' },
  { name: 'Pediatric Nephrology', route: '/services/pediatric-nephrology' },
  { name: 'Pediatric Neurology', route: '/services/pediatric-neurology' },
  { name: 'Pediatric Neurosurgery', route: '/services/pediatric-neurosurgery' },
  { name: 'Pediatric Ophthalmology & Strabismus', route: '/services/pediatric-ophthalmology-strabismus' },
  { name: 'Pediatric Orthopaedics', route: '/services/pediatric-orthopaedics' },
  { name: 'Pediatric Pain & Palliative Care', route: '/services/pediatric-pain-palliative-care' },
  { name: 'Pediatric Rheumatology', route: '/services/pediatric-rheumatology' },
  { name: 'Pediatric Surgery', route: '/services/pediatric-surgery' },
  { name: 'Pediatric Urology', route: '/services/pediatric-urology' },
  { name: 'Pelvic Health Physical Therapy', route: '/services/pelvic-health-physical-therapy' },
  { name: 'Peripheral Nerve Disorders', route: '/services/peripheral-nerve-disorders' },
  { name: 'Pharmaceutical Services', route: '/services/pharmatic-services' },
  { name: 'Pituitary & Skull Base Tumor', route: '/services/pituitary-skull-base-tumor' },
  { name: 'Plastic Surgery', route: '/services/plastic-surgery' },
  { name: 'Polycystic ovary syndrome (PCOS)', route: '/services/polycystic-ovary-syndrome-pcos' },
  { name: 'Precision Medicine', route: '/services/precision-medicine' },
  { name: 'Preventative Cardiology & Cardiometabolic Health', route: '/services/preventative-cardiology-cardiometabolic-health' },
  { name: 'Primary Care', route: '/services/primary-care' },
  { name: 'Primary Care at Home Program', route: '/services/primary-care-at-home-program' },
  { name: 'Prostate Cancer', route: '/services/prostate-cancer' },
  { name: 'Prostate Imaging and Treatment', route: '/services/prostate-imaging-and-treatment' },
  { name: 'Psychiatry', route: '/services/psychiatry' },
  { name: 'Pulmonary Rehabilitation', route: '/services/pulmonary-rehabilitation' },
  { name: 'Pulmonary Vascular Disease (PVD)', route: '/services/pulmonary-vascular-disease-pvd' },
  { name: 'Pulmonology & Critical Care', route: '/services/pulmonology-critical-care' },
  { name: 'Radiation Oncology', route: '/services/radiation-oncology' },
  { name: 'Radiology', route: '/services/radiology' },
  { name: 'Rape Treatment Center', route: '/services/rape-treatment-center' },
  { name: 'Refractive Surgery & Vision Correction', route: '/services/refractive-surgery-vision-correction' },
  { name: 'Rehabilitation Services & Care', route: '/services/rehabilitation-services-care' },
  { name: 'Reproductive Genetics', route: '/services/reproductive-genetics' },
  { name: 'Respiratory Care', route: '/services/respiratory-care' },
  { name: 'Retina Disease Care', route: '/services/retina-disease-care' },
  { name: 'Retinal Disorders & Ophthalmic Genetics', route: '/services/retinal-disorders-ophthalmic-genetics' },
  { name: 'Rheumatology', route: '/services/rheumatology' },
  { name: 'Robotic Surgery', route: '/services/robotic-surgery' },
  { name: 'Sarcoma', route: '/services/sarcoma' },
  { name: 'Scleroderma Care', route: '/services/scleroderma-care' },
  { name: 'Second Opinion', route: '/services/second-opinion' },
  { name: 'Shoulder and Elbow Surgery', route: '/services/shoulder-and-elbow-surgery' },
  { name: 'Sickle Cell Disease Care', route: '/services/sickle-cell-disease-care' },
  { name: 'Skeletal Dysplasia', route: '/services/skeletal-dysplasia' },
  { name: 'Skin Cancer', route: '/services/skin-cancer' },
  { name: 'Sleep Medicine', route: '/services/sleep-medicine' },
  { name: 'Small Bowel Endoscopy', route: '/services/small-bowel-endoscopy' },
  { name: 'South Asian Heart Health', route: '/services/south-asian-heart-health' },
  { name: 'Speech Pathology', route: '/services/speech-pathology' },
  { name: 'Spine Care', route: '/services/spine-care' },
  { name: 'Sports Cardiology', route: '/services/sports-cardiology' },
  { name: 'Sports Concussion and Traumatic Brain Injury', route: '/services/sports-concussion-and-traumatic-brain-injury' },
  { name: 'Sports Medicine', route: '/services/sports-medicine' },
  { name: 'Stomach Cancer', route: '/services/stomach-cancer' },
  { name: 'Stroke', route: '/services/stroke' },
  { name: 'Surgery', route: '/services/surgery' },
  { name: 'Surgical Oncology', route: '/services/surgical-oncology' },
  { name: 'Testicular Cancer', route: '/services/testicular-cancer' },
  { name: 'The Men\'s Clinic at UCLA', route: '/services/the-mens-clinic-at-ucla' },
  { name: 'Theranostics', route: '/services/theranostics' },
  { name: 'Thoracic Surgery', route: '/services/thoracic-surgery' },
  { name: 'Thyroid Care', route: '/services/thyroid-care' },
  { name: 'Transplant Services', route: '/services/transplant-services' },
  { name: 'Tumor-Infiltrating Lymphocyte (TIL) Therapy', route: '/services/tumor-infiltrating-lymphocyte-til-therapy' },
  { name: 'UCLA Health Well Check', route: '/services/ucla-health-well-check' },
  { name: 'UCLA Levine Family Center for Movement Disorders', route: '/services/ucla-levine-family-center-for-movement-disorders' },
  { name: 'Urogynecology & Pelvic Health', route: '/services/urogynecology-pelvic-health' },
  { name: 'Urologic Oncology', route: '/services/urologic-oncology' },
  { name: 'Urology', route: '/services/urology' },
  { name: 'Vascular and Endovascular Surgery', route: '/services/vascular-and-endovascular-surgery' },
  { name: 'Vascular Surgery for Varicose Veins', route: '/services/vascular-surgery-for-varicose-veins' },
  { name: 'Vasculitis Care', route: '/services/vasculitis-care' },
  { name: 'Vision Rehabilitation', route: '/services/vision-rehabilitation' },
  { name: 'Von Hippel-Lindau (VHL) Disease', route: '/services/von-hippel-lindau-vhl-disease' },
  { name: 'Walter and Shirley Wang Center for Integrative Digestive Health', route: '/services/walter-and-shirley-wang-center-for-integrative-digestive-health' },
  { name: 'Weight Management', route: '/services/weight-management' },
  { name: 'Women\'s Health & OBGYN Services', route: '/services/womens-health-obgyn-services' },
  { name: 'Women’s Cardiovascular Services', route: '/services/womens-cardiovascular-services' }
];

export const LETTERS = 'ABCDEFGHIJKLMNOPRSTUVW'.split('');

